<a href="https://colab.research.google.com/github/Thasli-ma-2004/Data-Analytics-using-Python-Project/blob/main/Internship_day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks = np.array([90,85,78,92])
print(marks[2])

78


In [ ]:
import numpy as np
#indexing- we got particular index value as op
#slicing-grp of elements we extract
marks = np.array([90,85,78,92])
print(marks[1:4])

[85 78 92]


In [ ]:
#student score analysis
import numpy as np
scores = np.array([85,76,92,99,44,89])

print("Scores:",scores [0:5])
print("Average Score:",np.mean(scores))
print("Highest Score:",np.max(scores))
print("Lowest Score:",np.min(scores))
print("Total Score:",np.sum(scores))

Scores: [85 76 92 99 44]
Average Score: 80.83333333333333
Highest Score: 99
Lowest Score: 44
Total Score: 485


In [ ]:
#sales array calculation
import numpy as np

sales=np.array([12000,15000,18000,14000,20000])
print("Sales:",sales)
print("Average Sales:",np.mean(sales))
print("Highest Sales:",np.max(sales))
print("Lowest Sales:",np.min(sales))
print("Total Sales:",np.sum(sales))


Sales: [12000 15000 18000 14000 20000]
Average Sales: 15800.0
Highest Sales: 20000
Lowest Sales: 12000
Total Sales: 79000


In [ ]:
#reshape and transpose
import numpy as np

arr= np.array([1,2,3,4,5,6,7,8,9])

a=arr.reshape(3,3)
b=a.T

print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
import numpy as np

marks= np.array([70,80,90,60])

average = np.mean(marks)

print(average)

75.0


In [ ]:
salary = np.array([10000,20000,30000,40000,50000])

med = np.median(salary)

print(med)

30000.0
