<a href="https://colab.research.google.com/github/Thasli-ma-2004/Data-Analytics-using-Python-Project/blob/main/internship_day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def attendance_percentage(attended,total):
  percentage=(attended/total)*100
  return round(percentage,2)

def check_eligibility(percent):
  if percent>=75:
    return 'ELIGIBLE'
  else:
    return 'NOT ELIGIBLE X'


try:
  total = int(input('Total Classes:'))
  attended = int(input('Classes Attended:'))

  pct = attendance_percentage(attended ,total)
  status = check_eligibility(pct)

  print(f'Attendance:{pct}%')
  print(f'Status:{status}')

except ValueError:
  print('Enter valid numbers!')

Total Classes:10
Classes Attended:8
Attendance:80.0%
Status:ELIGIBLE


In [ ]:
import numpy as np

marks = np.array([90,85,78,93])

print(marks)


[90 85 78 93]


In [ ]:
import numpy as np

students = np.array([
    [90, 85],
    [78,92],
    [88,95],
    [50,90]
])


print(students)



[[90 85]
 [78 92]
 [88 95]
 [50 90]]


In [ ]:
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
arr=np.arange(1,12)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
import numpy as np
arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
import numpy as np
arr=np.random.rand(4)
print(arr)

[0.02447235 0.008927   0.33920667 0.7580477 ]


In [ ]:
import numpy as np
matrix=np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

print(a+b)

print(a*b)

print(np.sqrt(a))

print(np.sum(a))

print(np.mean(b))

[11 22 33 44]
[ 10  40  90 160]
[1.         1.41421356 1.73205081 2.        ]
10
25.0
